config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'links#index'
  

  get 'links', to: 'links#index'                                     # Links index/homepage
  get 'links/new', to: 'links#new'                                   # New link form
  post 'links', to: 'links#create'                                   # Create link form action
  get 'link/:id', to: 'links#redirect', as: 'links_redirect'         # Redirect link to supplied url
  delete 'link/:id', to: 'links#destory', as: 'links_detroy'         # Destroys link and its comments
  get 'link/:id/edit', to: 'links#edit', as: 'links_edit'            # Link edit form
  patch 'link/:id', to: 'links#update', as: 'links_update'           # Update link form action

  get 'link/:id/comments', to: 'comments#show', as: 'comment_show'                         # Link, comments, comment form
  post 'link/:id/comments', to: 'comments#create'                                          # Create comment form action
  delete 'link/:link_id/comment/:comment_id', to: 'comments#destroy'                       # Destroys comment
  get 'link/:link_id/comment/:comment_id/edit', to: 'comments#edit'	                       # Comment edit form	
  patch 'link/:link_id/comment/:comment_id', to: 'comments#update', as: 'comment_update'   # Update comment form action

  get 'l/new', to: 'sublinkedit#new'                    # New sublinkedit form
  get 'l', to: 'sublinkedit#index'  			              # Index of all sublinkedits
  post 'l', to: 'sublinkedit#create'                    # Creates a new sublinkedit
  get 'l/:name', to: 'sublinkedit#show', as: 'l_show'		# Specific sublinkedit links index										

  get 'users/login', to: 'sessions#login'       # Login page
  post 'users/session', to: 'sessions#create'   # Sets session ID
  delete 'users/session', to: 'session#destory' # Destroys session ID

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :link
end

app/models/link.rb
class Link < ActiveRecord::Base
  has_many :comments, :dependent => :destroy
  belongs_to :user
  belongs_to :sublinkedit
end

app/models/sublinkedit.rb
class Sublinkedit < ActiveRecord::Base
  has_many :links
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :links
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def show
		# Will change according to voting score 
		@links = Link.order(created_at: :desc).limit(25)
		render :show
	end

	def create
		@link = Link.find(params[:link_id])
		@comment = Comment.create(content: params[:content], 
			 												user_id: params[:user_id], 
			 												link_id: params[:link_id])
		redirect_to comment_show_path(@link) 
	end

	def destroy
		@link = Link.find(params[:link_id])
		@comment = Comment.find(params[:comment_id])
		@comment.destroy
		redirect_to comment_show_path(@link) 
	end

	def edit
		@link = params[:link_id]
		@comment = Comment.find(params[:comment_id])
		@path = comment_update_path(@link, @comment.id) 
		@verb = :patch
		render :edit
	end

	def update
		@link = Link.find(params[:link_id])
		@comment = Comment.find(params[:comment_id])
		@comment.update_attributes(content: params[:content])
		redirect_to comment_show_path(@link) 
	end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  attr_accessor :title, :url

  def show
    @links = Link.order(created_at: :desc).limit(25)
    render :index
  end

  def new
    @link = links_path
    @action = :post
    @button = "Submit Link"
    render :new
  end

  def create
    @link = Link.create(title: params[:title], url: params[:url])
    flash[:notice] = "Your link has been successfully submitted"
    redirect_to :root
  end

  def edit
    @link = links_update_path
    @action = :patch
    @button = "Update"
    render :edit
  end

  def update
    @link = Link.find_by(id: params[:id])
    @link.update(title: params[:title], url: params[:url])
    redirect_to :root
  end

  def destroy
    @link = Link.find_by(id: params[:id])
    @link.destroy
    redirect_to :root
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def login
		@path = users_path
		render :login
	end

	def create
		@user = User.find_by(email: params[:email])
		passhash = Digest::SHA1.hexdigest(params[:password])

		if @user && @user.password == passhash
			session[:user_id] = @user.id
		else
			flash[:error] = "No user found with that email and password!"
		end
		redirect_to :root
	end

	def destroy
		session.delete(:user_id)
	end
	
end

app/controllers/sublinkedits_controller.rb
class SublinkeditsController < ApplicationController

	def new
		render :new
	end

	def index
		@sublinkedits = Sublinkedit.order(title: :asc)
		render :index
	end

	def create
		@sublinkedit = Sublinkedit.find_or_create_by(title: params[:title])
		redirect_to l_show_path(@sublinkedit.title)
	end

	def show
		@sublinkedit = Sublinkedit.find_by(title: params[:title])
		@links = Link.where(sub_id: @sublinkedit.id)
		render :show		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= form_tag(@path, method: @verb) do %>

  <div class="input">
    <%= label_tag(:content, 'Comment: ') %>
    <%= text_field_tag(:content, @comment.content, size: 40) %>
  </div>
  
  <br>

  <%= submit_tag("Save") %>

<% end %>

app/views/comments/_link.html.erb
<div class='link'>
  <div class="link_title"> 
    <%= link_to link.title, link.url %>
    <!-- <a href=<%= "#{link.url}" %>><%= "#{link.title}" %></a> -->
  </div>
  <div class="sumbit_time">
    <p class="submitted">submitted <%= "#{time_ago_in_words(link.created_at)}" %> ago </p>
  </div>
  <div class="link_comments">
    <%= link_to "#{link.comments.count} comments", comment_show_path(link) %>
  </div>
</div>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= render partial: 'form' %>

app/views/comments/show.html.erb
<h1>Links Index</h1>

<div class='links'>
  <% @links.each do |link| %>
    <%= render partial: 'link', object: link %>
    <br>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Linkedit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="notice"><%= flash[:notice] %></p>
  <p class="alert"><%= flash[:alert] %></p>

<%= yield %>

</body>
</html>

app/views/links/_form.html.erb
<%= form_tag(@link, method: @action) do %>

<div class="input">
  <div>
    <%= label_tag(:title, 'Title: ') %>
    <%= text_field_tag(:title, nil, size: 50) %>
  </div>

    </br>

  <div>
    <%=label_tag(:url, 'URL: ') %>
    <%=text_field_tag(:url, nil, size: 50) %>
  </div>

    </br>

  <div>
    <%= submit_tag(@button) %>
  </div>
</div>
<% end %>

app/views/links/edit.html.erb
<h2>Edit Link</h2>

<%= render partial: "form" %>

app/views/links/index.html.erb
<h2>Links Index</h2>

<div class='links'>
  <% @links.each do |link| %>
    <%= render partial: 'comments/link', object: link %>

    <br>

  <% end %>
</div>

app/views/links/new.html.erb
<h2>Submit Link</h2>

<%= render partial: "form" %>

app/views/sublinkedits/index.html.erb
<h1 class="sub-index">Sublinkedits</h1>

<div class="sublinkedits">
  <% @sublinkedits.each do |sub| %>
    <div class="sublinkedit">
      <%= link_to sub.title, l_show_path(sub) %>
    </div>

</div>
  

app/views/sublinkedits/new.html.erb
<%= form_tag(l_path, method: :post) do %>

  <div class="input">
    <%= label_tag(:title, "Name") %>
    <%= text_field_tag(:title, nil, size: 40) %>
  </div>

  <%= submit_tag("Create") %>

<% end %>

app/views/sublinkedits/show.html.erb
<h1 class="sub-show"><%= @sublinkedit.title %></h1>

<div class="links">
  <% @links.order(created_at: :desc).each do |link| %>
    <%= render partial: 'comments/link', object: link %>
    <br>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_tag(@user, method: @action) do %>

<div class="input">
    <div>
      <%= label_tag(:username, 'Name') %>
      <%= text_field_tag(:username, nil, size: 50) %>
    </div>

       </br>

    <div>
      <%= label_tag(:email, 'Email: ') %>
      <%= text_field_tag(:email, nil, size: 50) %>
    </div>

      </br>

    <div>
      <%= label_tag(:email, 'Confirm Email: ') %>
      <%= text_field_tag(:email, nil, size: 50) %>
    </div>

      </br>

    <div>
      <%= label_tag(:password, 'Password: ') %>
      <%= password_field_tag(:password, nil, size: 50) %>
    </div>

      </br>

    <div>
      <%= label_tag(:password, 'Confirm Password: ') %>
      <%= password_field_tag(:password, nil, size: 50) %>
    </div>

      </br>

    <div>
      <%= submit_tag(@button) %>
    </div>
  </div>

  <% end %>

app/views/users/edit.html.erb
<h2>Edit Account</h2>

<%= render partial: "form" %>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<%= render partial: "form" %>

  

app/views/users/show.html.erb
<%= render partial: "form" %>

<%= link_to "Edit Account", users_edit_path(@user) %>